"""add direction column to signals

Revision ID: 6212a9c22222
Revises: 2deb4780f39b
Create Date: 2026-03-30 22:42:00.541881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6212a9c22222'
down_revision: Union[str, Sequence[str], None] = '2deb4780f39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
