"""add suggested_estimates table and FK on user_estimates

Revision ID: b9a1c2ee5ca7
Revises: 6212a9c22222
Create Date: 2026-03-30 22:44:54.325988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a1c2ee5ca7'
down_revision: Union[str, Sequence[str], None] = '6212a9c22222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('anchor_prob_pct', sa.Float(), nullable=False),
    sa.Column('anchor_source', sa.String(), nullable=False),
    sa.Column('structural_adjustment', sa.Float(), nullable=False),
    sa.Column('signal_adjustment', sa.Float(), nullable=False),
    sa.Column('suggested_prob_pct', sa.Float(), nullable=False),
    sa.Column('composite_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.String(), nullable=False),
    sa.Column('decomposition_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('user_estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_estimate_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suggested_estimates', ['suggested_estimate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_estimates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suggested_estimate_id')

    op.drop_table('suggested_estimates')
    # ### end Alembic commands ###
