"""add outcome_name to market_lines

Revision ID: dcf07fbc0dc2
Revises: a742ecc66dc3
Create Date: 2026-03-28 13:19:13.639382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf07fbc0dc2'
down_revision: Union[str, Sequence[str], None] = 'a742ecc66dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_lines', schema=None) as batch_op:
        batch_op.drop_column('outcome_name')

    # ### end Alembic commands ###
